### ISSUE TITLE
/error or /success page not found

### ISSUE THREAD

**Issue by hostmahmud** [hazaveh/stripe-resellerclub#1]
after successful or unsuccessful payment the gateway redirect to /error or /success but it shows "page not found" after redirection

**Comment by hazaveh** [comment]
if you're on apache put the followin in your  .htaccess 
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]
```
if you're using nginx or iis, download the package from https://hazaveh.net/2020/10/integrate-stripe-into-resellerclub/ there are templates for those web servers.

**Comment by hostmahmud** [comment]
Thank you

**Comment by hostmahmud** [comment]
Another problem raised. After successful transaction, it is not redirecting to resellerclub clientarea panel. See screenshot https://prntscr.com/12v3ts1

**Comment by hazaveh** [comment]
This seems to be test mode from reseller club. Make a real payment
